### ISSUE TITLE
Conda Ccannot Find dmw51 Channel

### ISSUE THREAD

**Issue by licheng-xu-echo** [dmw51/reactiondataextractor#1]
When I run `conda install -c dmw51 ReactionDataExtractor` to install this package (in a new environment), errors show as below:

Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: dmw51
  channel url: https://conda.anaconda.org/dmw51
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

Is there any code I have missed before run `conda install -c dmw51 ReactionDataExtractor`?

**Comment by dmw51** [comment]
Hi!
Due to technical reasons, the channel name had to be changed to dmwil. Try running the following command:
`conda install -c dmwil ReactionDataExtractor`

I have updated the readme file to reflect this change.
