### ISSUE TITLE
__glibc errors prevent installation

### ISSUE THREAD

**Issue by ruslankotl** [dmw51/reactiondataextractor#3]
I am writing to ask about installation of Python Library called ReactionDataExtractor (https://anaconda.org/dmwil/reactiondataextractor) on z-gle, y-gle or t-gle machine.

The installation guide suggested creating a new Python 3.6 environment through `conda create -n extractor python=3.6`, then install the library by `conda install -c dmwil reactiondataextractor`

However, after following the instructions and allowing for flexible environment solve, the following message was obtained:

> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>  - feature:/linux-64::__glibc==2.27=0
>  - python=3.6 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
> 
> Your installed version is: 2.27
> 

The computers on which I tried to install the package are running Ubuntu 18.04

**Comment by dmw51** [comment]
Hi,

This is a problem related to the underlying OSRA/pyOSRA package. Based on the information provided it is difficult to provide a solution. I can see that glibc is not on the list of used packages - my suggestion is to try to install glib and gtk using:
````
sudo apt-get install libgtk2.0-dev
````
Alternatively, I have added an option to use the software via a docker container - I recommend this option for extracting data. Have a look [here](https://hub.docker.com/repository/docker/dmwil/reactiondataextractor).
